env:
  es6: true
  node: true
extends:
  - 'airbnb-base'
parser: babel-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
